# REGISTRASI MAHASISWA BARU

Registrasi merupakan prosedur awal bagi mahasiswa baru Universitas Sultan Ageng Tirtayasa. Mahasiswa Universitas Sultan Ageng Tirtayasa adalah mahasiswa yang telah menyelesaikan ketentuan dan prosedur yang berlaku. Pada prosesnya prosedur ini melibatkan 6 (enam) entitas, yaitu:

1. Mahasiswa.
2. Subbagian Registrasi & Statistik/BAKP. 
3. Subbagian Kemahasiswaan/BAKP.
4. Subbagian PNBP/BUKK.
5. Pusat Data dan Informasi (PUSDAINFO).
6. Jurusan/Program Studi/Fakultas/Pascasarjana.

## Ketentuan Mahasiswa Baru

Bagi calon mahasiswa baru sudah _**lulus tes seleksi**_ / ujian masuk perguruan tinggi di Universitas Sultan Ageng Tirtayasa melalui beberapa jalur masuk : Seleksi Nasional Masuk Perguruan Tinggi Negeri (SNMPTN) dengan Program Sarjana (S1), Seleksi Bersama Masuk Perguruan Tinggi Negeri (SBMPTN) dengan Program Sarjana (S1), Seleksi Masuk Mandiri Perguruan Tinggi Negeri (SMMPTN) dengan Program Sarjana (S1), Ujian Masuk Mandiri (UMM) dengan Program Diploma (D3) dan Seleksi Penerimaan Mahasiswa Baru (SPMB) dengan Program Magister (S2/S3) diselenggarakan oleh Pascasarjana  Universitas Sultan Ageng Tirtayasa.

Setelah lulus seleksi bukti lulusnya dituangkan dalam dokumen Surat Keputusan Rektor Universitas Sultan Ageng Tirtayasa  tentang  hasil seleksi penerimaan mahasiswa baru dari beberapa jalur masuk yang diterbitkan pada tahun akademik oleh Universitas Sultan Ageng Tirtayasa.

Selanjutnya calon mahasiswa melengkapi persyaratan administrasi akademik dan administrasi keuangan / sudah membayar Uang Kuliah Tunggal (UKT)/ Sumbangan Pengembangan Pendidikan (SPP) bagi mahasiswa baru Program Sarjana (S1) dan Program Diploma (D3) dan calon mahasiswa melengkapi persyaratan administrasi akademik dan administrasi keuangan serta sudah membayar Sumbangan Pengembangan Pendidikan (SPP) bagi mahasiswa baru Program Magister (S2/S3).

Bagi mahasiswa baru baik Program Sarjana (S1) dan Program Diploma (D3) melakukan registrasi akademik dengan melengkapi persyaratan dan ketentuan yang telah ditetapkan.

## Waktu Registrasi

Pelaksanaan registrasi mahasiswa baru mengacu pada ketentuan yang telah di tuangkan dalam kalender akademik pada semester gasal (Program Sarjana (S1) dan Diploma (D3), semester gasal dan genap (Program Magister (S2)) sehingga mahasiswa sudah punya dasar dan gambaran yang pasti akan waktu pelaksanaan kegiatan Registrasi Mahasiswa Baru tersebut dan proses perkuliahan dapat berjalan dengan baik.

## Prosedur Persyaratan Mahasiswa Baru

### Mahasiswa Baru

Calon mahasiswa melihat informasi ke [http://admisi.untirta.ac.id](http://admisi.untirta.ac.id),

a. Surat Keputusan Rektor Tentang Hasil Seleksi Mahasiswa Baru sesuai dengan  jalur masuk  SNMPTN, SBMPTN, SMMPTN, UMM.
b. Pengumuman Registrasi mahasiswa baru sesuai dengan jalur masuk SNMPTN, SBMPTN, SMMPTN, UMM.
c. Alur Registrasi Mahasiswa Baru sesuai dengan jalur masuk SNMPTN, SBMPTN, SMMPTN, UMM.

### Pengisian/Pengambilan Persyaratan Berkas Registrasi

Calon Mahasiswa Baru *login* ke http://admisi.untirta.ac.id, dengan *username*: Nomor Peserta SNMPTN, SBMPTN, SMMPTN, UMM serta *password*: Tanggal Lahir.

a. Pengisian Biodata Mahasiswa dan mengunggah Foto terbaru (latar belakang merah dan memakai kemeja putih).
b. Mengunduh Pakta Integritas Uang Kuliah Tunggal (UKT)/Biaya Pendidikan
c. Mengunduh dan Surat Pernyataan Mentaati Peraturan Untirta

### Data Pendukung Lampiran Berkas Registrasi

Calon Mahasiswa Baru setelah melengkapi persyaratan, *login* kembali ke http://admisi.untirta.ac.id dan kemudian **WAJIB** mengunggah seluruh persyaratan tanpa terkecuali antara lain:

a. Hasil pindah (*scan*) Kartu Peserta SNMPTN, SBMPTN, SMMPTN, UMM.
b. Hasil pindai Ijazah atau SKHUN atau Surat Keterangan Lulus (SKL) bagi yang belum keluar ijasahnya. 
c. Hasil pindai Tes Kesehatan
d. Hasil pindai Tes Narkoba
e. Hasil pindai Tes Buta Warna bagi jurusan tertentu:

    1. **FKIP** : Penddikan Biologi, Pendidikan Kimia, Pendidikan Fisika, Pendidikan IPA, Pendidikan Teknik Elektro, Pendidikan Teknik Mesin. PAUD.
    2. **Fakultas Teknik** : Teknik Kimia, Teknik Metalurgi, Teknik Mesin, Teknik Elektro.
    3. **Fakultas Pertanian** : Agribisnis, Agroekoteknologi, Perikanan, Teknologi Pangan.
    4. **Fakultas Kedokteran** : Keperawatan (D3).

f. Hasil pindai Akte Kelahiran.
g. Hasil pindai Tagihan Rekening Listrik Bulan terbaru dan tahun  berjalan
h. Hasil pindai Pajak Bumi dan Bagunan (PBB) terbaru.
i. Hasil pindai Kartu Keluarga (KK).
j. Hasil pindai Slip Pengasilan orang tua bagi calon mahasiswa yang orang tuanya bekerja sebagai PNS/Swasta, yang ditanda-tangani oleh pejabat/pimpinan instansi tempat kerja, atau Hasil pindai Surat Keterangan Penghasilan yang ditandatangani oleh kelurahan atau kecamatan, jika orang tua bekerja sebagai Wiraswasta / Pedagang / Buruh / Petani / Pensiunan. (Jika kedua orang tua bekerja).

### Verifikasi data registrasi oleh Subbagian Registrasi dan Statistik terhadap data yang telah diunggah oleh calon mahasiswa baru

Tim dari Subbagian Registrasi dan statitik akan memeriksa data yang telah diunggah. Apabila data yang diunggah tidak lengkap maka tim akan menghubungi calon mahasiwa baru tersebut. Data ini diperlukan untuk menentukan dasar penentuan besaran UKT calon mahasiswa baru

### Pengisian/Pengambilan Persyaratan Berkas Registrasi Program Magister (S2)

Calon Mahasiswa Baru pengambilan persyaratan di Subbagian Akademik Pascasarjana, Universitas Sultan Ageng Tirtayasa. Persyaratan yang harus dilengkapi calon mahasiswa baru:

a. Kartu Tanda Peserta Ujian SPMB 
b. Pengisian Biodata Mahasiswa.
c. Ijazah S1, Akta IV (bagi yang memiliki AKTA IV) dan Transkrip Akademik di legalisir/Surat Keterangan Lulus asli bagi yang belum keluar Ijazah, Akta IV dan Transkrip Akademik.
d. Slip Pembayaran SPP.  
e. Pas Photo terbaru berwarna (ukuran: 3x4): 2 Lembar.

## Biro Akademik, Kemahasiswaan, dan Perencanaan (BAKP)

### Subbagian Registrasi dan Statistik memverifikasi Berkas Registrasi Mahasiswa Baru

#### Program Sarjana (S1) dan Diploma (D3)

Bagi calon mahasiswa setelah melakukan pengisian / pengambilan persyaratan registrasi secara *online* (mengunduh dan mengunggah), persyaratan poin 3 nomor 3.1. – 3.6 dan 3.12 – 3.13 dibawa untuk dicek kebenarannya (membawa persyaratan asli) Ke Subbagian Registrasi dan Statistik, Biro Akademik, Kemahasiswaan dan Perencanaan (BAKP).


#### Program Magister (S2)

Bagi calon mahasiswa setelah melakukan pengisian/pengambilan persyaratan dan sudah melengkapi persyaratan registrasi diserahkan ke Subbagian Akademik Pascasarjana, berkas persayaratan tersebut secara kolektif oleh Subbagian Akademik Pascasarjana di serahkan ke Subbagian Registrasi dan Statistik (BAKP) untuk diverifikasi.


### Subbagian Kemahasiswaan memverifikasi Berkas Bidikmisi Mahasiswa Baru Program Sarjana (S1)

Bagi Calon Mahasiswa Bidikmisi di harap melakukan registrasi Bidikmisi dengan melengkapi persyaratan sebagai mahasiswa baru Bidikmisi dengan menyerahkan persyaratan Bidikmisi untuk di verifikasi berkas Bidikmisi ke Subbagian Kemahasiswaan, Biro Akademik, Kemahasiswaan, dan Perencanaan (BAKP), diantaranya:

a. Kopi Kartu Tanda Penduduk (KTP).
b. Kopi Kartu Keluarga (KK).
c. Kopi Kartu Indonesia Pintar.
d. Surat Keterangan Tidak Mampu (SKTM) dari kelurahan setempat.
e. Kopi Rekening Listrik (Bulan Terakhir).
f. Slip Penghasilan Orang Tua/Slip Gaji
g. Pas Photo Ukuran 3x4 Berwarna = 2 Lembar.
h. Photo Rumah Tinggal Ukuran Poscard Berwarna, dengan ketentuan sebagai berikut:

    - Photo Rumah Tapak Depan.
    - Photo Rumah Tampak Belakang.
    - Photo Ruang Dapur    

i. Mengisi Form Surat Pernyataan Bermaterai Beasiswa Bidikmisi (Form bisa dapat di Subbagian Kemahasiswaan)
j. Esai yang ditulis tangan tentang kondisi perekonomian, rutinitas belajar dan kondisi keluarga, dalam kertas folio bergaris maksimal 2 lembar dan ditandatangani.

Semua berkas tersebut dimasukan ke dalam map berwarna dengan ketentuan sebagai berikut:

- Fakultas Hukum: MERAH.
- Fakultas Keguruan dan Ilmu Pendidikan: HIJAU. 
- Fakultas Teknik: BIRU.
- Fakultas Ekonomi: KUNING.
- Fakultas Pertanian: COKLAT.
- Fakultas Ilmu Sosial dan Ilmu Politik: ORANGE.
- Fakultas Kedokteran:


> Catatan :

> 1. Proses Verifikasi tidak dapat diwakilkan dan harus hadir sesuai dengan jadwal registrasi yang telah ditetapkan.

> 2. Bagi calon mahasiswa yang tidak melakukan registrasi dan pembayaran UKT pada tanggal yang telah ditetapkan dianggap **MENGUNDURKAN DIRI**.

> 3. Bagi Calon Mahasiswa Bidikmisi diharap melakukan registrasi Akademik dengan melengkapi persyaratan sebagai mahasiswa secara online dan menyerahkan persyaratan aslinya ke Subbagian Registrasi dan Statistik, Biro Akademik, Kemahasiswaan dan Perencanaan (BAKP), untuk diverifikasi.

> 4. Bagi calon mahasiswa yang tidak melakukan registrasi pemberkasan Mahasiswa Baru Bidikmisi pada tanggal yang telah ditetapkan dianggap MENGUNDURKAN DIRI.


## Biro Umum, Keuangan, dan Kepegawaian

**Subbagian Penerimaan Bukan Pajak (PNBP) memverifikasi Berkas Registrasi Mahasiswa Baru**

Bagi calon mahasiswa setelah melakukan pengisian/pengambilan persyaratan registrasi secara *online* (mengunduh dan mengunggah), persyaratan poin 1 nomor 7-11 akan diverifikasi oleh Subbagian Penerimaan Bukan Pajak (PNBP) Biro Umum Keuangan dan Kepegawaian (BUKK) dan sebagai dasar untuk menentukan besaran UKT yang akan diterima oleh Mahasiswa Baru.

> **Catatan** :

> 1. Proses Registrasi bagi Mahasiswa Warga Negara Asing (WNA) didampingi oleh UPT Pusat Layanan Internasional (PLI) Untirta.

> 2. Ketentuan umum yang berlaku bagi Mahasiswa Warga Negara Asing (WNA) mengikuti ketentuan yang berlaku di Kementerian Riset Teknologi dan Pendidikan Tinggi Republik Indonesia.


## Bank (BNI 46)

### Program Sarjana (S1) dan Diploma (D3).

Pembayaran Uang Kuliah Tunggal (UKT)  berdasarkan PERMENDIKBUD No.50 Tentang Uang Kuliah Tunggal (UKT) yang disesuaikan berdasarkan data penghasil orang tua/kedua orang tua jika kedua orang tua memiliki/mendapatkan penghasilan yang diberikan sebagai persyaratan mahasiswa  baru, dituangkan dalam dokumen Surat Keputusan Rektor Universitas Sultan Ageng Tirtayasa tentang  Penetapan Biaya Pendidikan Uang Kuliah Tunggal (UKT) Bagi Mahasiswa Baru Program Sarjana (S1) dan Diploma (D3) dari beberapa jalur masuk  pada tahun akademik oleh Universitas Sultan Ageng Tirtayasa. Pembayaran dilakukan di seluruh cabang Bank BNI, dengan menyebutkan nomor ujian, sesuai dengan jadwal yang telah ditentukan.

### Program Magister (S2)

Pembayaran Sumbangan Pengembangan Pendidikan (SPP) berdasarkan penetapan Surat Keputusan Rektor Tentang Penetapan Besaran Pembayaran Sumbangan Pengembangan Pendidikan (SPP), Bagi Mahasiswa Baru Program Magister (S2) berdasarkan penerimaan mahasiswa baru pada tahun masuk/gelombang. Pembayaran dilakukan di seluruh cabang Bank BNI, dengan menyebutkan nomor ujian sesuai dengan jadwal yang telah ditentukan.

### Kartu Tanda Mahasiswa (KTM plus ATM)

Kartu Tanda Mahasiswa (KTM) yang juga berfungsi sebagai ATM, diberikan kepada mahasiswa baru setelah menyelesaikan persyaratan akademik, keuangan, sudah mendapatkan Nomor Induk Mahasiswa (NIM) dan sudah mendapatkan dari Kartu Tanda Mahasiswa (KTM) Sementara, serta sudah membuka rekening Bank BNI Cabang Serang, sebagai persyaratan pembuatan KTM/ATM yang berfungsi sebagai identitas mahasiswa Universitas Sultan Ageng Tirtayasa yang dikeluarkan oleh Bank BNI Cabang Serang.

## Subbagian Registrasi dan Statistik - BAKP

### Program Sarjana (S1) dan Program Diploma (D3)

**Pemberian Nomor Induk (NIM) dan PIN**

Pemberian Nomor Induk Mahasiswa (NIM) setelah  melengkapi persyaratan tersebut di atas maka mahasiswa  baru diberikan Nomor Induk Mahasiswa (NIM) diverifikasi sebagai identitas mahasiswa dan pemberian PIN setelah diverifikasi sebagai Password untuk melakukan registrasi on-line SIAKAD : pengisian / pengambilan mata kuliah / Kartu Rencana Studi (KRS) Program Sarjana dan Diploma (D3),  Nomor Induk Mahasiswa (NIM) dan PIN diberikan di Sub.Bagian Registrasi dan Statistik, Biro Akademik, Kemahasiswaan dan Perencanaan (BAKP).

**Keterangan:**
Nomor Induk Mahasiswa (NIM) yang terdiri-dari kode Fakultas, Kode Jurusan/Program Studi, Kode Angkatan dan Nomor Urut Mahasiswa.

**Identifikasi Kode:**
Fakultas: 2 (dua) digit.
Jurusan/Program Studi: 2 (dua) digit.
Tahun Masuk/Angkatan: 2 (dua) digit.
Nomor Urut: 4 (empat) digit.

**Contoh**: Fakultas: Hukum, Program Studi: Ilmu Hukum, NIM: 1111160001.

### Program Magister (S2)

**Pemberian Nomor Induk (NIM)**

Pemberian Nomor Induk Mahasiswa (NIM) diverifikasi sebagai identitas mahasiswa setelah melengkapi persyaratan tersebut di atas, maka mahasiswa baru diberikan Nomor Induk Mahasiswa (NIM) secara kolektif dari Sub.Bagian Registrasi dan Statistik, Biro Akademik, Kemahasiswaan dan Perencanaan (BAKP) diserahkan ke Sub.Bagian Akademik Pascasarjana.  Pengambilan Nomor Induk Mahasiswa (NIM) ke Sub.Bagian Akademik Pascasarjana. 

**Keterangan:**
Nomor Induk Mahasiswa (NIM) yang terdiri-dari Kode Pascasarjana, Kode Program Studi, Kode Angkatan dan   Nomor Urut Mahasiswa.

**Identifikasi Kode:**
Pascasarjana: 2 (dua) digit.
Program Studi: 2 (dua) digit.
Tahun Masuk/Angkatan: 2 (dua) digit.
Nomor Urut: 4 (empat) digit.

**Contoh**: Pascarjana, Program Studi: Pendidikan Bahasa Indonesia, NIM: 7771160001.

### Kartu Tanda Mahasiswa (KTM) Sementara.

Kartu Tanda Mahasiswa (KTM) Sementara diberikan kepada mahasiswa baru setelah menyelesaikan persyaratan akademik, keuangan dan sudah mendapatkan Nomor Induk Mahasiswa (NIM), yang sifatnya KTM sementara sebagai identitas mahasiswa  diberikan di bagian Sub Bagian Registrasi dan Statistik BAKP.

## Pusat Data dan Informasi (PUSDAINFO)

**Program Sarjana (S1) dan Diploma (D3)**

Pusat data dan Informasi (PUSDAINFO) menyiapkan Aplikasi Sistem Registrasi *Online* /SIREG *Online* dan Aplikasi Sistem Akademik *Online*/SIAKAD *Online* berupa elektronik.

## Prosedur Kontrak Mata Kuliah

## Petugas Registrasi

